{% set version = "2.10.8" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "2.0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: 235a40bec7346c7b82b6a8caae0456353dc06e71f14bc414bcc858af1838719a

build:
  number: 0
  run_exports:
    - sigcpp-{{ abi_version }} >={{ version }}

outputs:
  - name: sigcpp-{{ abi_version }}
    script: build_libsigcpp.sh  # [unix]
    script: build_libsigcpp.bat  # [win]
    build:
      run_exports:
        - sigcpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - meson
        - ninja
      run_constrained:
        - libsigcpp {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libsigc-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\sigc-{{ abi_version }}-0.dll exit 1  # [win]

  - name: libsigcpp
    requirements:
      run:
        - sigcpp-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/sigc++-{{ abi_version }}.pc  # [unix]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\sigc++-{{ abi_version }}.pc exit 1  # [win]

about:
  home: https://libsigcplusplus.github.io/libsigcplusplus/
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: libsigc++ implements a typesafe callback system for standard C++
  dev_url: https://github.com/libsigcplusplus/libsigcplusplus
  doc_url: https://libsigcplusplus.github.io/libsigcplusplus/doc.html

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
    - tschoonj
