{% set version = "3.2.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "3.0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  fn: libsigc++-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: 8cdcb986e3f0a7c5b4474aa3c833d676e62469509f4899110ddf118f04082651

build:
  number: 0
  run_exports:
    - sigcpp-{{ abi_version }} >={{ version }}

outputs:
  - name: sigcpp-{{ abi_version }}
    script: build_libsigcpp.sh  # [unix]
    script: build_libsigcpp.bat  # [win]
    build:
      run_exports:
        - sigcpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - meson
        - ninja
      run_constrained:
        - libsigcpp {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - test -f ${PREFIX}/lib/libsigc-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\sigc-{{ abi_version }}-0.dll exit 1  # [win]
        - pkg-config --exact-version {{ version }} sigc++-{{ abi_version }}

  - name: libsigcpp
    requirements:
      run:
        - sigcpp-{{ abi_version }}  {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exact-version {{ version }} sigc++-{{ abi_version }}

about:
  home: http://libsigc.sourceforge.net/
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: libsigc++ implements a typesafe callback system for standard C++.

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
    - tschoonj
