{% set version = "3.2.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "3.0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  fn: libsigc++-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: 8cdcb986e3f0a7c5b4474aa3c833d676e62469509f4899110ddf118f04082651

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - sigcpp-{{ abi_version }} >={{ version }}

outputs:
  - name: sigcpp-{{ abi_version }}
    script: build_libsigcpp.sh
    build:
      run_exports:
        - sigcpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - meson
        - ninja
      run_constrained:
        - libsigcpp {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libsigc-{{ abi_version }}${SHLIB_EXT}

  - name: libsigcpp
    requirements:
      run:
        - sigcpp-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/sigc++-{{ abi_version }}.pc

about:
  home: http://libsigc.sourceforge.net/
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: libsigc++ implements a typesafe callback system for standard C++.

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
