{% set major_minor = "2.10" %}
{% set version = major_minor + ".0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  fn: libsigc++-{{ version }}.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: f843d6346260bfcb4426259e314512b99e296e8ca241d771d21ac64f28298d81

build:
  number: 0
#  features:
#    - vc9   # [win and py27]
#    - vc10  # [win and py34]
#    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain  # [unix]
    - autoconf   # [unix]
    - automake   # [unix]
    - m4         # [unix]
    - toolchain
    - make
    - m2w64-toolchain  # [win]
  run:
    - m2w64-gcc-libs   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libsigc-2.0.so  # [linux]
    - test -f ${PREFIX}/lib/libsigc-2.0.dylib  # [osx]

about:
  home: http://libsigc.sourceforge.net/
  license: LGPL v3
  license_file: COPYING
  summary: "libsigc++ implements a typesafe callback system for standard C++."

extra:
  recipe-maintainers:
    - scopatz
