{% set version = "2.10.7" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "2.0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  url: http://ftp.acc.umu.se/pub/GNOME/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: d082a2ce72c750f66b1a415abe3e852df2eae1e8af53010f4ac2ea261a478832

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - sigcpp-{{ abi_version }} >={{ version }}

outputs:
  - name: sigcpp-{{ abi_version }}
    script: build_libsigcpp.sh
    build:
      run_exports:
        - sigcpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - gnuconfig
        - autoconf
        - automake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - meson
        - ninja
        - make  # [unix]
      host:
        - m4
      run_constrained:
        - libsigcpp {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libsigc-{{ abi_version }}${SHLIB_EXT}

  - name: libsigcpp
    requirements:
      run:
        - sigcpp-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/sigc++-{{ abi_version }}.pc

about:
  home: https://libsigcplusplus.github.io/libsigcplusplus/
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: libsigc++ implements a typesafe callback system for standard C++
  dev_url: https://github.com/libsigcplusplus/libsigcplusplus
  doc_url: https://libsigcplusplus.github.io/libsigcplusplus/doc.html

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
